a = input('Digite algo: ')
print('O tipo primitivo de {} é:'.format(a), type(a))
print('{} é um número?'.format(a), a.isnumeric())
print('{} é alfanumérico?'.format(a), a.isalnum())
print('{} é alfabético?'.format(a), a.isalpha())
print('{} é decimal?'.format(a), a.isdecimal())
print('{} é ascii?'.format(a), a.isascii())
print('{} é formado por dígitos?'.format(a), a.isdigit())
print('{} é identifier?'.format(a), a.isidentifier())
print('{} está em minúsculas?'.format(a), a.islower())
print('{} está em maiúsculas?'.format(a), a.isupper())
print('{} só tem espaços?'.format(a), a.isspace())
print('{} é imprimível?'.format(a), a.isprintable())
print('{} está capitalizada?'.format(a), a.istitle())
